# -*- coding: utf-8 -*-
"""HTML_Quick_Styler_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjlM6zyTHNgsW9LPdEfqSopKn6PG4hw4
"""

pip install gradio transformers torch accelerate

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

class ColorPaletteGenerator:

    def __init__(self):

        self.palettes = {

            "modern": {
                "primary": "#6366F1",
                "secondary": "#8B5CF6",
                "accent": "#06B6D4",
                "background": "#0F172A",
                "text": "#F8FAFC"
            },

            "ocean": {
                "primary": "#0284C7",
                "secondary": "#0EA5E9",
                "accent": "#38BDF8",
                "background": "#082F49",
                "text": "#E0F2FE"
            },

            "forest": {
                "primary": "#15803D",
                "secondary": "#22C55E",
                "accent": "#4ADE80",
                "background": "#052E16",
                "text": "#DCFCE7"
            }
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

def generate_css(palette):

    css = f"""

    body {{
        margin:0;
        font-family:Arial;
        background:{palette['background']};
        color:{palette['text']};
    }}

    header {{
        background:{palette['primary']};
        padding:60px;
        text-align:center;
    }}

    section {{
        padding:40px;
    }}

    .features {{
        display:grid;
        grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
        gap:20px;
    }}

    .btn {{
        background:{palette['accent']};
        padding:12px 20px;
        border:none;
        color:white;
    }}

    footer {{
        background:{palette['secondary']};
        text-align:center;
        padding:20px;
    }}

    """

    return css

class HTMLPageBuilder:

    def __init__(self, palette):
        self.palette = palette

    def build_page(self, title, description):

        css = generate_css(self.palette)

        html = f"""

        <!DOCTYPE html>
        <html>

        <head>
        <title>{title}</title>

        <style>
        {css}
        </style>

        </head>

        <body>

        <header>
        <h1>{title}</h1>
        <p>{description}</p>
        </header>

        <section>
        <h2>About</h2>
        <p>This website was generated automatically.</p>
        </section>

        <section>
        <h2>Features</h2>

        <div class="features">

        <div>
        <h3>AI Generated</h3>
        <p>Automatic website creation</p>
        </div>

        <div>
        <h3>Responsive</h3>
        <p>Works on mobile and desktop</p>
        </div>

        <div>
        <h3>Modern UI</h3>
        <p>Professional design layout</p>
        </div>

        </div>

        </section>

        <footer>
        <p>© HTML Quick Styler</p>
        </footer>

        </body>
        </html>

        """

        return html

def generate_ai_content(prompt):

    inputs = tokenizer(prompt, return_tensors="pt")

    outputs = model.generate(
        **inputs,
        max_length=200
    )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text

palette_generator = ColorPaletteGenerator()

def generate_website(title, description, style):

    palette = palette_generator.get_palette(style)

    builder = HTMLPageBuilder(palette)

    html = builder.build_page(title, description)

    return html, html

with gr.Blocks() as app:

    gr.Markdown("# HTML Quick Styler")

    with gr.Tab("Generate Page"):

        title = gr.Textbox(label="Page Title")

        description = gr.Textbox(label="Page Description")

        style = gr.Dropdown(
            ["modern","ocean","forest"],
            label="Color Style"
        )

        generate_button = gr.Button("Generate Website")

        html_output = gr.Code(label="Generated HTML")

    with gr.Tab("Live Preview"):

        preview = gr.HTML()

    generate_button.click(
        generate_website,
        inputs=[title, description, style],
        outputs=[html_output, preview]
    )

app.launch(share=True)